### ISSUE TITLE
メール通知機能を実装する

### ISSUE THREAD

**Issue by shoma2da** [meyasubaco/notifier#7]
https://www.parse.com/apps/handshakejp/collections#class/Application/objectId/3r7Zt3mBxX
Parseのデータの to_mail を見てユーザ登録してあるメールアドレスに通知メールを送る。

**Comment by shoma2da** [comment]
herokuのaddon対応とかでやろうとすると有料になりそうなので、一旦止まりました。。

**Comment by himaratsu** [comment]
メールはなくてもいいかなw
ダッシュボードからの返信機能が重要

**Comment by shoma2da** [comment]
閉じちゃいましょうか！
